import assert from "node:assert/strict";
import { describe, it } from "node:test";
import jsQR from "jsqr";
import { encodeQr } from "../../../server/qr.js";
import { pairingTokenFromQr } from "./pairing-token.ts";

const origin = "https://mac.example.ts.net";
const token = "a".repeat(43);

describe("pairingTokenFromQr", () => {
  it("accepts only a valid same-origin HTTPS pairing link", () => {
    assert.equal(pairingTokenFromQr(`${origin}/#pair=${token}`, origin), token);
    assert.equal(pairingTokenFromQr(`https://other.example/#pair=${token}`, origin), null);
    assert.equal(pairingTokenFromQr(`http://mac.example.ts.net/#pair=${token}`, origin), null);
    assert.equal(pairingTokenFromQr(`${origin}/#pair=short`, origin), null);
    assert.equal(pairingTokenFromQr(token, origin), null);
  });

  it("decodes the QR code generated by the pairing CLI", () => {
    const value = `${origin}/#pair=${token}`;
    const matrix = encodeQr(value);
    const quiet = 4;
    const scale = 6;
    const modules = matrix.length + quiet * 2;
    const size = modules * scale;
    const pixels = new Uint8ClampedArray(size * size * 4).fill(255);
    for (let y = 0; y < matrix.length; y += 1) {
      for (let x = 0; x < matrix.length; x += 1) {
        if (!matrix[y][x]) continue;
        for (let py = 0; py < scale; py += 1) {
          for (let px = 0; px < scale; px += 1) {
            const offset = (((y + quiet) * scale + py) * size + (x + quiet) * scale + px) * 4;
            pixels[offset] = pixels[offset + 1] = pixels[offset + 2] = 0;
          }
        }
      }
    }
    assert.equal(jsQR(pixels, size, size)?.data, value);
  });
});
